name: Solar System Workflow

on: 
    workflow_dispatch: 
    push: 
        branches: 
            - main
            - 'feature/*'
env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{vars.MONGO_USERNAME}}
  MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD}}  
jobs:
    unit-testing:
        name: Unit Testing
        services:
          mongo-db:
            image: siddharth67/mongo-db:non-prod
            ports:
              - 27017:27017
        env:
            MONGO_URI: 'mongodb://localhost:27017/superData'
            MONGO_USERNAME: non-prod-user
            MONGO_PASSWORD: non-prod-password 
        strategy:
          matrix:
            nodejs_version: [18, 20]
            os: [ubuntu-latest]
            exclude:
              - nodejs_version: 18
                os: macos-latest
        runs-on: ${{matrix.os}}
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            - name: Setup NodeJs Version - ${{matrix.nodejs_version}}
              uses: actions/setup-node@v4
              with:
                node-version: ${{matrix.nodejs_version}}
            - name: Cache NPM dependencies
              uses: actions/cache@v4.0.2
              with:
                path: node_modules
                key: ${{runner.os}}-node-modules-${{hashFiles('package-lock.json')}}
            - name: Install Dependencies
              run: npm install
            - name: Unit Testing
              id: nodejs-unit-testing-step
              run: npm test
            - name: Archive Test Result
              if: always()
              uses: actions/upload-artifact@v4.4.0
              with:
                name: Mocha-Test-Result-${{matrix.nodejs_version}}-${{matrix.os}}
                path: test-results.xml
    code-coverage:
        runs-on: ubuntu-latest
        container: 
          image: node:18
        services:
            mongo-db:
              image: siddharth67/mongo-db:non-prod
              options: 
                --name mongo
              ports:
                - 27017:27017
        env:
            MONGO_URI: 'mongodb://mongo:27017/superData'
            MONGO_USERNAME: non-prod-user
            MONGO_PASSWORD: non-prod-password 
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            # - name: Setup NodeJs Version - 18
            #   uses: actions/setup-node@v4
            #   with:
            #     node-version: 18
            - name: Cache NPM dependencies
              uses: actions/cache@v4.0.2
              with:
                  path: node_modules
                  key: ${{runner.os}}-node-modules-${{hashFiles('package-lock.json')}}

            - name: Install Dependencies
              run: npm install 
            - name: check Code Coverage
              continue-on-error: true
              run: npm run coverage
            - name: Archive Coverage Result
              uses: actions/upload-artifact@v4.4.0
              with:
                name: Code Coverage Result
                path: coverage
                retention-days: 5
    docker:
        name: Containerization
        runs-on: ubuntu-latest
        permissions: 
            packages: write
        needs: [unit-testing, code-coverage]
        steps:
          - name: Checkout Repo
            uses: actions/checkout@v4
            
          - name: Dockerhub Login
            uses: docker/login-action@v3.3.0
            with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}
          - name: Github Container Registry Login
            uses: docker/login-action@v3.3.0
            with:
                registry: ghcr.io
                username: ${{ github.repository_owner }}
                password: ${{ secrets.GITHUB_TOKEN }}

          - name: Build Build For Testing
            uses: docker/build-push-action@v6.7.0
            with:
              context: .
              push: false
              tags: ${{secrets.DOCKERHUB_USERNAME}}/solar-system:${{github.sha}}
            
          - name: Docker Image Testing
            run: |
                docker images
                docker run --name solar-system-app -d \
                -p 3000:3000 \
                -e MONGO_URI=$MONGO_URI \
                -e MONGO_USERNAME=$MONGO_USERNAME \
                -e MONGO_PASSWORD=$MONGO_PASSWORD \
                "${{secrets.DOCKERHUB_USERNAME}}/solar-system:${{github.sha}}"
                
                export IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' solar-system-app)
                echo $IP
                echo Testing Image URL using wget
                wget -q -O - 127.0.0.1:3000/live | grep live
          - name: Container Registry Push
            uses: docker/build-push-action@v6.7.0
            with:
                context: .
                push: true
                tags: |
                    ${{secrets.DOCKERHUB_USERNAME}}/solar-system:${{github.sha}}
                    ghcr.io/faresgabsi/solar-system:${{github.sha}}
    dev-deploy:
      needs: docker
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: Install kubectl CLI
          uses: Azure/setup-kubectl@v4.0.0
          with:
            version: 'v1.26.0'
        - name: Set Kubeconfig 
          uses: azure/k8s-set-context@v4
          with:
              method: kubeconfig
              kubeconfig: ${{secrets.KUBECONFIG}}
        - name: Fetch Kubernetes Cluster Details
          run: |
            kubectl version --short -o yaml
            echo --------------------------------------
            kubectl get nodes

        - name: Save Nginx Ingress Controller Ip as a GITHUB ENV Variable
          run: |
            echo "INGRESS_IP=$(kubectl -n ingress-nginx get services ingress-nginx-controller -o jsonpath="{.status.loadBalancer.ingress[0].ip}")" >> $GITHUB_ENV
        - name: Replace Token in Manifest files
          uses: cschleiden/replace-tokens@v1
          with:
            tokenPrefix: '_{_'
            tokenSuffix: '_}_'
            files: '["kubernetes/development/*.yaml"]'
          env:
            NAMESPACE: ${{vars.NAMESPACE}}
            REPLICAS: ${{vars.REPLICAS}}
            IMAGE: ${{secrets.DOCKERHUB_USERNAME}}/solar-system:${{github.sha}}
            INGRESS_IP: ${{secrets.INGRESS_IP}}
        - name: Check files
          run: |
            cat kubernetes/development/*.yaml
        - name: Create MongoDB Secret
          run: |
            kubectl -n ${{vars.NAMESPACE}} create secret generic mongo-db-creds \
            --from-literal=MONGO_URI=${{env.MONGO_URI}} \
            --from-literal=MONGO_USERNAME=${{env.MONGO_USERNAME}} \
            --from-literal=MONGO_PASSWORD=${{env.MONGO_PASSWORD}} \
            --save-config \
            --dry-run=client \
            -o yaml | kubectl apply -f -
        - name: Deploy to Dev env
          run: |
            kubectl apply -f kubernetes/development

